### ISSUE TITLE
Datadog exporter

### ISSUE THREAD

**Issue by jared-mackey** [open-telemetry/opentelemetry-erlang-api#60]
I would love to see a datadog exporter. Especially with support for span analytics out of the box. 

I don’t know erlang very well or else I’d be super happy to jump in and help. Willing to contribute to an elixir one if that makes sense to do so.

**Comment by hauleth** [comment]
It is better to have one in Erlang as it would allow to use it in more applications, especially as building Elixir projects from Rebar3 isn't that easy. In past I have written one for OpenTelemetry when that was still a thing so I can help you with that, but as I am not using DD currently I will not work directly on that right now.

**Comment by tsloughter** [comment]
I think @hauleth meant OpenCensus?

Note that you can use the Otel collector to be able to export to many different services https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/exporter and https://github.com/open-telemetry/opentelemetry-collector/tree/master/exporter

DataDog isn't one of them yet, so doesn't help you at the moment.

Obviously it is great to have them also available in Erlang/Elixir to not require using the collector, I just wanted to mention it.

With @hauleth 's help and we have the Spandex devs, @GregMefford @zachdaniel involved, we should be able to get a great DataDog exporter put together :).

@hauleth is also right that Elixir projects from rebar3 is not as well supported as I'd like.. But I would like to be forced to improve that experience :). Honeycomb exporter is in Elixir so that one I will be working on improving the rebar3-mix experience around.

It is also easy enough to convert Elixir to Erlang (at least in a case like an exporter where there isn't need for macros) so I wouldn't want to discourage development of exporters written in Elixir :)

**Comment by hauleth** [comment]
Yeah, I meant OpenCensus. Too many names…
