### ISSUE TITLE
Automated benchmarking and regression checks in CI

### ISSUE THREAD

**Issue by tolbrino** [open-telemetry/opentelemetry-erlang-api#72]
In order to verify that changes have no severe impact on the performance overhead of using this SDK, the CI should be used to do micro-benchmarking and checking the results for regressions. The steps involved could be something like this:

- Run micro-benchmark on every PR and branch
- Store results as artifacts somewhere where they can be fetched
- After PR micro-benchmark, try to fetch latest results for `master`
- Compare results and post difference as message in the PR
- Merging of PRs should always be possible, but at that point the reviewers are informed and aware of the impact

**Comment by hauleth** [comment]
The problem with this is that it is **enormously hard** to do right. Mostly due to fact that we would need separate, physical machine for running such tests, as without repeatable environment and with unknown **real CPU** usage it is hard to see reasonable results in such microbenchmarking.

And such benchmark can vary from VM version to VM version, between different CPUs, between different memory bandwidths, between different OSes, between different compilers used for VM building, between different libraries versions used for building VM, etc.

**Comment by tolbrino** [comment]
I agree. This could also be handled by a bot which does have access to a dedicated machine.

At the very least such a check would be useful even if run manually by the PR creator pre and post PR.
